apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-privileged-containers
spec:
  validationFailureAction: Enforce
  rules:
    - name: deny-privileged-containers
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "Privileged containers are not allowed"
        foreach:
          - list: "request.object.spec.containers[]"
            deny:
              conditions:
                all:
                  - key: "{{ element.securityContext.privileged || `false` }}"
                    operator: Equals
                    value: true

    - name: deny-privileged-init-containers
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "Privileged init containers are not allowed"
        foreach:
          - list: "request.object.spec.initContainers[]"
            deny:
              conditions:
                all:
                  - key: "{{ element.securityContext.privileged || `false` }}"
                    operator: Equals
                    value: true